### ISSUE TITLE
Launch checklist

### ISSUE THREAD

**Issue by feiphoon** [feiphoon/github-workshop#22]
- [x] Make repository public
- [x] Check task numbering #20 
- [x] Check that workshop material is accessible from the front page #21 
- [x] Share link with support team (Chiin, Sandrine, Alison, Julian, Marisa)
- [x] Check guest list & add Julian & Marisa to it
- [x] Add repository description
- [x] Generate latest PDF of slides
- [x] Upload slides PDF to Github and Speakerdeck
- [x] Slides test on screen in the Prow (may have to adjust ratio) 5:30pm on the day
- [x] Guest list (no need to submit to security). Any volunteer checks it downstairs, Kobalt person pops down to get guests
- [x] Leave a Kobalt person's phone number downstairs.
- [x] Get a whiteboard

If we have time/nice-to-have:
- [ ] Set up workshop material on Jekyll/Github Pages
- [ ] Cheatsheet? Or is that no longer needed

Come from 6pm, be here by 6:30pm, start at 7pm.
